### PR TITLE
Shaved down version of kenny starter first person shooter player

### PR DESCRIPTION
**Pull request by MariusTH**

### CODE REVIEW

**Comment by sean-sinclair** [comment]
@MariusTH Fantastic! Could be a great start! 

Could you run the gdlint and resolve the linting issues in a new commit and I'll accept and merge 👍🏼

**Review by sean-sinclair — APPROVED** [review]

**Review by sean-sinclair — APPROVED** [review]
LGTM

**Comment by sean-sinclair** [comment]
Huh, my approval aint good enough it seems 😅

**Comment by MariusTH** [comment]
Need some supreme approval 😆

**Review by SeanTSinclair — APPROVED** [review]
LGTM

**Comment by SeanTSinclair** [comment]
Supreme approval granted

Was on the wrong GH acc 😓

**Pull request merged**
